### ISSUE TITLE
ERROR: When i try to install

### ISSUE THREAD

**Issue by Rajeshr34** [amazingSurge/jquery-asScrollable#1]
`$ bower install --allow-root jquery-asScrollable -S`

`bower ENOTFOUND     Package jquery-asScrollable not found`

**Comment by amazingSurge** [comment]
Hi, We will register our plugin to bower soon.

**Comment by amazingSurge** [comment]
Or you can try use bower install git@github.com:amazingSurge/jquery-asScrollable.git this time.

**Comment by incoqnito** [comment]
when i want to install it, every time he asks for a fingerprint and than i cant download it. I have bought your remark template and when i run

    bower install asscrollable

it returns following output 

    $ bower install git@github.com:amazingSurge/jquery-asScrollable.git
    bower not-cached    git@github.com:amazingSurge/jquery-asScrollable.git#*
    bower resolve       git@github.com:amazingSurge/jquery-asScrollable.git#*
    The authenticity of host 'github.com (192.30.252.128)' can't be established.
    RSA key fingerprint is ###############################################.
    Are you sure you want to continue connecting (yes/no)? yes 
    bower checkout      jquery-asScrollable#master
    The authenticity of host 'github.com (192.30.252.128)' can't be established.
    RSA key fingerprint is ###############################################.
    Are you sure you want to continue connecting (yes/no)? yes
    bower resolved      git@github.com:amazingSurge/jquery-asScrollable.git#c875fab05b
    bower not-cached    git@github.com:amazingSurge/jquery-asScrollbar.git#*
    bower resolve       git@github.com:amazingSurge/jquery-asScrollbar.git#*
    bower cached        git@github.com:brandonaaron/jquery-mousewheel.git#3.1.13
    bower validate      3.1.13 against git@github.com:brandonaaron/jquery-mousewheel.git#*
    bower cached        git://github.com/jquery/jquery.git#2.1.4
    bower validate      2.1.4 against git://github.com/jquery/jquery.git#>=2.1.1
    bower cached        git://github.com/imsky/holder.git#2.4.1
    bower validate      2.4.1 against git://github.com/imsky/holder.git#~2.4.1
    The authenticity of host 'github.com (192.30.252.128)' can't be established.
    RSA key fingerprint is ###############################################.
    Are you sure you want to continue connecting (yes/no)? The authenticity of host 'github.com (192.30.252.128)' can't be established.
    RSA key fingerprint is ###############################################.
    Are you sure you want to continue connecting (yes/no)?     bower cached        git://github.com/jquery/jquery.git#2.1.4
    bower validate      2.1.4 against git://github.com/jquery/jquery.git#>= 1.9.1
    bower cached        git://github.com/jquery/jquery.git#2.1.4
    bower validate      2.1.4 against git://github.com/jquery/jquery.git#>=1.11.0
    bower cached        git://github.com/jquery/jquery.git#2.1.4
    bower validate      2.1.4 against git://github.com/jquery/jquery.git#>=1.2.2
    bower cached        git://github.com/jquery/jquery.git#2.1.4
    bower validate      2.1.4 against git://github.com/jquery/jquery.git#>=1.8.3
    bower cached        git://github.com/jquery/jquery.git#2.1.4
    bower validate      2.1.4 against git://github.com/jquery/jquery.git#>= 1.11.0
    bower cached        git://github.com/jquery/jquery.git#2.1.4
    bower validate      2.1.4 against git://github.com/jquery/jquery.git#>=1.6.2
    bower cached        git://github.com/jquery/jquery.git#2.1.4
    bower validate      2.1.4 against git://github.com/jquery/jquery.git#>= 1.2.6
    bower cached        git://github.com/jquery/jquery.git#2.1.4
    bower validate      2.1.4 against git://github.com/jquery/jquery.git#>= 2.1.0
    bower cached        git://github.com/jquery/jquery.git#2.1.4
    bower validate      2.1.4 against git://github.com/jquery/jquery.git#>=1.6
    bower cached        git://github.com/jquery/jquery.git#2.1.4
    bower validate      2.1.4 against git://github.com/jquery/jquery.git#>=1.4.4
    bower cached        git://github.com/jquery/jquery.git#2.1.4
    bower validate      2.1.4 against git://github.com/jquery/jquery.git#>=1.7.0
    bower cached        git://github.com/jquery/jquery.git#2.1.4
    bower validate      2.1.4 against git://github.com/jquery/jquery.git#>=1.7
    bower cached        git://github.com/jquery/jquery.git#2.1.4
    bower validate      2.1.4 against git://github.com/jquery/jquery.git#>= 1.9.0
    bower cached        git://github.com/jquery/jquery.git#2.1.4
    bower validate      2.1.4 against git://github.com/jquery/jquery.git#>=1.9.1
    bower cached        git://github.com/jquery/jquery.git#2.1.4
    bower validate      2.1.4 against git://github.com/jquery/jquery.git#>= 1.8.0
    ^C

Any solution? i have tried it with `ignoredDependencies`, `suppliedDependencies` but nothing work
