### ISSUE TITLE
ERROR 404: "jquery-wheel" not found when Install

### ISSUE THREAD

**Issue by Clyff** [amazingSurge/jquery-asScrollable#2]
When i add this package via composer or run: `composer require bower-asset/asscrollable:~0.3.1`

I got the follow error:

```
[Composer\Downloader\TransportException]
  The "https://bower.herokuapp.com/packages/search/jquery-wheel" file could n
  ot be downloaded (HTTP/1.1 404 Not Found)
```

I saw that you guys have as dependency:

```
 "jquery-wheel": "git@github.com:brandonaaron/jquery-mousewheel.git",
```

But this repository does not exists anymore.

**Comment by aaronchi** [comment]
"jquery-wheel": "git@github.com:jquery/jquery-mousewheel.git",
