### ISSUE TITLE
ERROR: Unable to Bower Install caused by jquery-asScrollbar

### ISSUE THREAD

**Issue by danielwalton11** [amazingSurge/jquery-asScrollable#4]
**Error Response:** Failed to execute "git ls-remote --tags --heads git@github.com:amazingSurge/jquery-asScrollbar.git", exit code of #128 Permission denied (publickey). fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

Can manually clone via HTTP but automated Bower install fails.

**Comment by biggieman** [comment]
+1 to this problem

**Comment by allnetru** [comment]
Probably you should make SSH public key and put it in your https://github.com/settings/keys (we reproduced exactly the same error and it helps).

Also modify "git@github.com:amazingSurge/jquery-asScrollbar.git" to "https://github.com/amazingSurge/jquery-asScrollbar.git" in bower.json can help.

**Comment by amazingSurge** [comment]
Thanks for reporting. We will submit it to npm and bower later.
