### ISSUE TITLE
asScrollable don`t work right - on bootstrap modal

### ISSUE THREAD

**Issue by csplkiller** [amazingSurge/jquery-asScrollable#5]
asScrollable do not work right - on bootstrap modal
**How i can fix it** ? Width of scroll div 0px;
jQuery JavaScript Library v1.11.3
jQuery asScrollable v0.4.7
jQuery asScrollbar v0.5.4

![2017-02-27_19-31-37](https://cloud.githubusercontent.com/assets/7470513/23369745/6c8613aa-fd23-11e6-9e09-60dcbfb5078f.png)

When I change the size of the browser window, the problem disappears.

![2017-02-27_19-34-27](https://cloud.githubusercontent.com/assets/7470513/23369857/c99a96d8-fd23-11e6-84e8-82e490083fe9.png)

excuse me for my bad English

**Comment by amazingSurge** [comment]
Hi,

You should initialize the scrollable when modal shown.

http://getbootstrap.com/javascript/#modals
```
$('#myModal').on('shown.bs.modal', function () {
  // initialize code here.
})
```

Regards.
